In [1]:
import torch
import numpy as np

from cnn.numpy_model import Conv2d
from scripts.make_init_weights import (
    conv_weights_converter, conv_biases_converter
)

In [2]:
def compare_conv2d(kernel_size, stride, kernel_center, padding=0):
    # random input array
    input_array = np.random.rand(1, 5, 5).astype(np.float32)
    
    # torch Conv2d
    torch_conv2d = torch.nn.Conv2d(1, 1, kernel_size, stride, padding=padding)
    print("torch Conv2d:")
    input_tensor = torch.from_numpy(input_array).unsqueeze(0)
    print(torch_conv2d(input_tensor))

    # numpy implementation of Conv2d
    numpy_conv2d = Conv2d(
        kernel_size=kernel_size,
        in_channels=1,
        out_channels=1,
        stride=stride,
        kernel_center=kernel_center,
        padding=padding,
        convolution=False
    )
    # convert weights from torch conv2d to numpy conv2d
    numpy_conv2d.conv_w = conv_weights_converter(torch_conv2d.state_dict()['weight'])
    numpy_conv2d.conv_b = conv_biases_converter(torch_conv2d.state_dict()['bias'])

    print("\nNumpy implementation of Conv2d:")
    print(numpy_conv2d(input_array))

## Compare torch Conv2d to numpy-implementation

#### Kernel center is always in (0, 0) position

### Kernel size (2, 2) and stride 2

In [3]:
compare_conv2d(
    kernel_size=(2, 2),
    stride=2,
    kernel_center=(0, 0)
)

torch Conv2d:
tensor([[[[-0.1412,  0.0377],
          [-0.0248, -0.3575]]]], grad_fn=<ThnnConv2DBackward>)

Numpy implementation of Conv2d:
[array([[-0.14116088,  0.03771617],
       [-0.02484168, -0.3575285 ]], dtype=float32)]


### Kernel size (3, 3) and stride 1

In [4]:
compare_conv2d(
    kernel_size=(3, 3),
    stride=1,
    kernel_center=(0, 0)
)

torch Conv2d:
tensor([[[[-0.2305, -0.4262, -0.1277],
          [ 0.0419,  0.0482,  0.1126],
          [-0.0532, -0.0479, -0.4103]]]], grad_fn=<ThnnConv2DBackward>)

Numpy implementation of Conv2d:
[array([[-0.23051777, -0.42615947, -0.12774153],
       [ 0.04185531,  0.04824102,  0.11260903],
       [-0.05322258, -0.04785229, -0.41027802]], dtype=float32)]


### Kernel size (4, 4) and stride 2

In [5]:
compare_conv2d(
    kernel_size=(4, 4),
    stride=2,
    kernel_center=(0, 0)
)

torch Conv2d:
tensor([[[[-0.4054]]]], grad_fn=<MkldnnConvolutionBackward>)

Numpy implementation of Conv2d:
[array([[-0.4054127]], dtype=float32)]


### Kernel size (3, 3), stride 2, padding 3

In [6]:
compare_conv2d(
    kernel_size=(3, 3),
    stride=2,
    kernel_center=(0, 0),
    padding=3
)

torch Conv2d:
tensor([[[[-0.0197, -0.0197, -0.0197, -0.0197, -0.0197],
          [-0.0197,  0.2750,  0.4760,  0.2583, -0.0197],
          [-0.0197,  0.3465,  0.6443,  0.5811, -0.0197],
          [-0.0197,  0.0123,  0.1295,  0.1442, -0.0197],
          [-0.0197, -0.0197, -0.0197, -0.0197, -0.0197]]]],
       grad_fn=<ThnnConv2DBackward>)

Numpy implementation of Conv2d:
[array([[-0.0196629 , -0.0196629 , -0.0196629 , -0.0196629 , -0.0196629 ],
       [-0.0196629 ,  0.27500707,  0.47599107,  0.2583431 , -0.0196629 ],
       [-0.0196629 ,  0.34646586,  0.64431113,  0.5810625 , -0.0196629 ],
       [-0.0196629 ,  0.01227409,  0.12945685,  0.14419107, -0.0196629 ],
       [-0.0196629 , -0.0196629 , -0.0196629 , -0.0196629 , -0.0196629 ]],
      dtype=float32)]
