In [1]:
import torch
import numpy as np

from cnn.numpy_model import Conv2d
from scripts.make_init_weights import (
    conv_weights_converter, conv_biases_converter
)

In [2]:
def compare_conv2d(kernel_size, stride, kernel_center, padding=0):
    # random input array
    input_array = np.random.rand(1, 5, 5).astype(np.float32)
    
    # torch Conv2d
    torch_conv2d = torch.nn.Conv2d(1, 1, kernel_size, stride, padding=padding)
    print("torch Conv2d:")
    input_tensor = torch.from_numpy(input_array).unsqueeze(0)
    print(torch_conv2d(input_tensor))

    # numpy implementation of Conv2d
    numpy_conv2d = Conv2d(
        kernel_size=kernel_size,
        in_channels=1,
        out_channels=1,
        stride=stride,
        kernel_center=kernel_center,
        padding=padding,
        convolution=False
    )
    # convert weights from torch conv2d to numpy conv2d
    numpy_conv2d.conv_w = conv_weights_converter(torch_conv2d.state_dict()['weight'])
    numpy_conv2d.conv_b = conv_biases_converter(torch_conv2d.state_dict()['bias'])

    print("\nNumpy implementation of Conv2d:")
    print(numpy_conv2d(input_array))

## Compare torch Conv2d to numpy-implementation

#### Kernel center is always in (0, 0) position

### Kernel size (2, 2) and stride 2

In [3]:
compare_conv2d(
    kernel_size=(2, 2),
    stride=2,
    kernel_center=(0, 0)
)

torch Conv2d:
tensor([[[[-0.2998, -0.3680],
          [-0.5606, -0.4098]]]], grad_fn=<ThnnConv2DBackward>)

Numpy implementation of Conv2d:
[array([[-0.29976724, -0.36797103],
       [-0.56061949, -0.40979104]])]


### Kernel size (3, 3) and stride 1

In [4]:
compare_conv2d(
    kernel_size=(3, 3),
    stride=1,
    kernel_center=(0, 0)
)

torch Conv2d:
tensor([[[[ 0.4767,  0.1116,  0.0358],
          [ 0.3911,  0.0581,  0.4450],
          [ 0.2346, -0.0311,  0.0658]]]], grad_fn=<ThnnConv2DBackward>)

Numpy implementation of Conv2d:
[array([[ 0.47665877,  0.11160256,  0.03579822],
       [ 0.39114232,  0.05808807,  0.44496372],
       [ 0.23458593, -0.03111989,  0.0658099 ]])]


### Kernel size (4, 4) and stride 2

In [5]:
compare_conv2d(
    kernel_size=(4, 4),
    stride=2,
    kernel_center=(0, 0)
)

torch Conv2d:
tensor([[[[0.4226]]]], grad_fn=<MkldnnConvolutionBackward>)

Numpy implementation of Conv2d:
[array([[0.42262959]])]


### Kernel size (3, 3), stride 2, padding 3

In [6]:
compare_conv2d(
    kernel_size=(3, 3),
    stride=2,
    kernel_center=(0, 0),
    padding=3
)

torch Conv2d:
tensor([[[[0.2034, 0.2034, 0.2034, 0.2034, 0.2034],
          [0.2034, 0.3960, 0.6389, 0.4219, 0.2034],
          [0.2034, 0.5173, 1.2061, 0.8548, 0.2034],
          [0.2034, 0.6608, 0.8985, 0.7719, 0.2034],
          [0.2034, 0.2034, 0.2034, 0.2034, 0.2034]]]],
       grad_fn=<ThnnConv2DBackward>)

Numpy implementation of Conv2d:
[array([[0.20339541, 0.20339541, 0.20339541, 0.20339541, 0.20339541],
       [0.20339541, 0.39604704, 0.63892502, 0.42186425, 0.20339541],
       [0.20339541, 0.5173453 , 1.20608855, 0.85484172, 0.20339541],
       [0.20339541, 0.66082276, 0.89851127, 0.77189236, 0.20339541],
       [0.20339541, 0.20339541, 0.20339541, 0.20339541, 0.20339541]])]
