In [1]:
import numpy as np

from cnn.numpy_model import Conv2d

In [2]:
dEdx_l = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

y_l_minus_1 = np.zeros((6, 6))

##  View convolution backprop operations through weight kernel on each step

### With stride=1 the dE/dx<sup>l</sup> preserves the order of its elements.

In [3]:
conv2d = Conv2d(
    kernel_size=(2, 2),
    in_channels=1,
    out_channels=1,
    stride=1,
    kernel_center=(0, 0),
    convolution=False
)

x = conv2d.convolution_back_dEdw_l(y_l_minus_1, dEdx_l, print_demo=True)

a=0; b=0
 [[ 1.  2.  3.  4.  0.  0.]
 [ 5.  6.  7.  8.  0.  0.]
 [ 9. 10. 11. 12.  0.  0.]
 [13. 14. 15. 16.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
a=0; b=1
 [[ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0. 13. 14. 15. 16.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
a=1; b=0
 [[ 0.  0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  0.  0.]
 [ 5.  6.  7.  8.  0.  0.]
 [ 9. 10. 11. 12.  0.  0.]
 [13. 14. 15. 16.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
a=1; b=1
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0. 13. 14. 15. 16.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


### But with stride=2 the dE/dx<sup>l</sup>  "decays" and zeros appear between its elements.

In [4]:
conv2d = Conv2d(
    kernel_size=(2, 2),
    in_channels=1,
    out_channels=1,
    stride=2,
    kernel_center=(0, 0),
    convolution=False
)

x = conv2d.convolution_back_dEdw_l(y_l_minus_1, dEdx_l, print_demo=True)

a=0; b=0
 [[ 1.  0.  2.  0.  3.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 5.  0.  6.  0.  7.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 9.  0. 10.  0. 11.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
a=0; b=1
 [[ 0.  1.  0.  2.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  5.  0.  6.  0.  7.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  9.  0. 10.  0. 11.]
 [ 0.  0.  0.  0.  0.  0.]]
a=1; b=0
 [[ 0.  0.  0.  0.  0.  0.]
 [ 1.  0.  2.  0.  3.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 5.  0.  6.  0.  7.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 9.  0. 10.  0. 11.  0.]]
a=1; b=1
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  2.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  5.  0.  6.  0.  7.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  9.  0. 10.  0. 11.]]
