In [1]:
import numpy as np

from cnn.numpy_model import Conv2d

In [2]:
kernel = np.array([
    [1, 2],
    [3, 4]
])

dEdx_l = np.zeros((3, 3))

##  View <u>convolution</u> backprop operations through input matrix y<sup>l-1</sup> on each step

### It is worth noting that the kernel retains its orientation on dE/dx<sup>l</sup> matrix, while during feedforward <u>convolution</u> step the kernel was turned upside down on y<sup>l-1</sup> (and It is vice versa for <u>cross-correlation</u>).

In [3]:
conv2d = Conv2d(
    kernel_size=(2, 2),
    in_channels=1,
    out_channels=1,
    stride=1,
    kernel_center=(0, 0),
    convolution=True
)

x = conv2d.convolution_back_dEdy_l_minus_1(dEdx_l, kernel, (3, 3), print_demo=True)

i=0; j=0
 [[1. 2. 0.]
 [3. 4. 0.]
 [0. 0. 0.]]
i=0; j=1
 [[0. 1. 2.]
 [0. 3. 4.]
 [0. 0. 0.]]
i=0; j=2
 [[0. 0. 1.]
 [0. 0. 3.]
 [0. 0. 0.]]
i=1; j=0
 [[0. 0. 0.]
 [1. 2. 0.]
 [3. 4. 0.]]
i=1; j=1
 [[0. 0. 0.]
 [0. 1. 2.]
 [0. 3. 4.]]
i=1; j=2
 [[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 3.]]
i=2; j=0
 [[0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 0.]]
i=2; j=1
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]]
i=2; j=2
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


### With stride=2 the kernel "decays" and zeros appear between its elements.

In [4]:
conv2d = Conv2d(
    kernel_size=(2, 2),
    in_channels=1,
    out_channels=1,
    stride=2,
    kernel_center=(0, 0),
    convolution=True
)


x = conv2d.convolution_back_dEdy_l_minus_1(dEdx_l, kernel, (2, 2), print_demo=True)

i=0; j=0
 [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
i=0; j=1
 [[0. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
i=1; j=0
 [[0. 0. 0.]
 [3. 0. 0.]
 [0. 0. 0.]]
i=1; j=1
 [[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 0.]]
