In [1]:
import numpy as np

from cnn.numpy_model import Conv2d

In [2]:
kernel = np.array([
    [1, 2],
    [3, 4]
])

y_l_minus_1 = np.zeros((3, 3))

##  View <u>convolution</u> operations on each step

### The kernel is turned upside down on y<sup>l-1</sup>

In [3]:
conv2d = Conv2d(
    kernel_size=(2, 2),
    in_channels=1,
    out_channels=1,
    stride=1,
    kernel_center=(0, 0),
    convolution=True
)

x = conv2d.convolution_feed_x_l(y_l_minus_1, kernel, print_demo=True)

i=0; j=0
 [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
i=0; j=1
 [[2. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
i=1; j=0
 [[3. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
i=1; j=1
 [[4. 3. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]


##  View <u>cross-correlation</u> operations on each step

### The kernel retains its orientation on y<sup>l-1</sup>

In [4]:
conv2d = Conv2d(
    kernel_size=(2, 2),
    in_channels=1,
    out_channels=1,
    stride=1,
    kernel_center=(0, 0),
    convolution=False
)

x = conv2d.convolution_feed_x_l(y_l_minus_1, kernel, print_demo=True)

i=0; j=0
 [[1. 2. 0.]
 [3. 4. 0.]
 [0. 0. 0.]]
i=0; j=1
 [[0. 1. 2.]
 [0. 3. 4.]
 [0. 0. 0.]]
i=1; j=0
 [[0. 0. 0.]
 [1. 2. 0.]
 [3. 4. 0.]]
i=1; j=1
 [[0. 0. 0.]
 [0. 1. 2.]
 [0. 3. 4.]]
